import { auth } from "@/auth";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, BarChart3, FileCheck2, Route, Search, ShieldCheck, Truck } from "lucide-react";

export default async function HomePage() {
  const session = await auth();
  if (session?.user) redirect("/dashboard");
  const features = [
    { icon: Truck, title: "Flotta sotto controllo", text: "Mezzi, documenti, scadenze e autisti in un unico ambiente." },
    { icon: Route, title: "Viaggi senza frammenti", text: "Assegna, monitora e raccogli DDT e aggiornamenti dall'autista." },
    { icon: BarChart3, title: "Margini e dati utili", text: "Leggi performance di mezzi, autisti e viaggi, non solo grafici." },
  ];
  return <main className="min-h-screen bg-slate-950 text-slate-100">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="flex items-center gap-2 font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-tr from-blue-600 to-indigo-500"><Truck className="h-5 w-5" /></span>Truck Radar</Link><div className="flex items-center gap-4 text-sm"><Link href="/login" className="text-slate-300 hover:text-white">Accedi</Link><Link href="/register" className="rounded-xl bg-blue-600 px-4 py-2 font-semibold hover:bg-blue-500">Registra la tua azienda</Link></div></nav>
    <section className="mx-auto grid max-w-6xl gap-12 px-6 pb-20 pt-16 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="mb-5 inline-flex items-center gap-2 rounded-full border border-blue-800/60 bg-blue-950/50 px-3 py-1 text-xs font-semibold text-blue-200"><ShieldCheck className="h-3.5 w-3.5" />Per aziende di trasporto</p><h1 className="max-w-3xl text-5xl font-bold leading-[1.04] tracking-tight md:text-6xl">Meno chilometri a vuoto. Più controllo su ogni viaggio.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">Truck Radar riunisce flotta, autisti, viaggi, documenti e opportunità di ritorno in un solo sistema operativo per il trasporto.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/login" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-semibold shadow-lg shadow-blue-600/20 hover:bg-blue-500">Inizia ad usare Truck Radar <ArrowRight className="h-4 w-4" /></Link><Link href="/cerca-un-vettore" className="inline-flex items-center gap-2 rounded-xl bg-rose-700 px-5 py-3 font-semibold shadow-lg shadow-rose-900/30 hover:bg-rose-600"><Search className="h-4 w-4" /> Cerca un vettore</Link></div><p className="mt-4 text-center text-xs text-slate-500">Trial operativo. Il Network è riservato alle aziende verificate.</p></div><div className="rounded-3xl border border-slate-800 bg-gradient-to-br from-slate-900 to-slate-950 p-6 shadow-2xl"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Il flusso Truck Radar</p><div className="mt-6 space-y-3">{["Organizza mezzi, autisti e viaggi", "Raccogli DDT e stato consegna", "Collega dati e leggi i margini", "Accedi al Network verificato"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-950/70 p-4"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-blue-950 text-xs font-bold text-blue-300">{index + 1}</span><span className="text-sm font-medium">{item}</span></div>)}</div></div></section>
    <section className="border-y border-slate-800 bg-slate-900/50"><div className="mx-auto grid max-w-6xl gap-5 px-6 py-16 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><Icon className="h-6 w-6 text-blue-400" /><h2 className="mt-4 text-lg font-bold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></section>
    <section className="mx-auto max-w-6xl px-6 py-20"><div className="grid gap-10 rounded-3xl border border-emerald-900/60 bg-emerald-950/20 p-8 md:grid-cols-2"><div><FileCheck2 className="h-7 w-7 text-emerald-400" /><h2 className="mt-4 text-3xl font-bold">Un Network basato sulla fiducia.</h2></div><div className="text-sm leading-7 text-slate-300">Puoi usare il gestionale subito. Per pubblicare carichi, subappaltare e accedere alle opportunità del Network, l&apos;azienda completa una verifica con documenti societari e identità del rappresentante. I dati sensibili vengono gestiti tramite fornitori specializzati.</div></div></section>
    <footer className="border-t border-slate-800 px-6 py-8"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-3 text-xs text-slate-500 md:flex-row"><span>© {new Date().getFullYear()} Truck Radar · Transport Operating System</span><div className="flex items-center gap-4"><Link href="/privacy" className="hover:text-slate-300">Privacy</Link><Link href="/informativa-autisti" className="hover:text-slate-300">Autisti</Link><Link href="/termini" className="hover:text-slate-300">Termini</Link><Link href="/cookie" className="hover:text-slate-300">Cookie</Link></div></div></footer>
  </main>;
}